#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script de traduction automatique pour le fichier fr.json
"""

import json
import re

# Dictionnaire de traduction des termes courants
translations = {
    # Verbes
    "Add": "Ajouter",
    "Added": "Ajouté",
    "Apply": "Appliquer",
    "Cancel": "Annuler",
    "Cancelled": "Annulé",
    "Change": "Changer",
    "Choose": "Choisir",
    "Close": "Fermer",
    "Closed": "Fermé",
    "Complete": "Complet",
    "Completed": "Terminé",
    "Confirm": "Confirmer",
    "Confirmed": "Confirmé",
    "Continue": "Continuer",
    "Convert": "Convertir",
    "Converted": "Converti",
    "Copy": "Copier",
    "Copied": "Copié",
    "Delete": "Supprimer",
    "Deleted": "Supprimé",
    "Deliver": "Livrer",
    "Delivered": "Livré",
    "Download": "Télécharger",
    "Edit": "Modifier",
    "Enter": "Entrer",
    "Enjoy": "Profiter",
    "Explore": "Explorer",
    "Failed": "Échoué",
    "Filter": "Filtrer",
    "Find": "Trouver",
    "Follow": "Suivre",
    "Get": "Obtenir",
    "Give": "Donner",
    "Join": "Rejoindre",
    "Login": "Connexion",
    "Logout": "Déconnexion",
    "Order": "Commander",
    "Ordered": "Commandé",
    "Pay": "Payer",
    "Paid": "Payé",
    "Pending": "En attente",
    "Pick": "Choisir",
    "Picked": "Choisi",
    "Place": "Placer",
    "Placed": "Placé",
    "Please": "Veuillez",
    "Processing": "En cours",
    "Provide": "Fournir",
    "Rate": "Noter",
    "Rating": "Évaluation",
    "Ratings": "Évaluations",
    "Received": "Reçu",
    "Receiver": "Destinataire",
    "Refund": "Remboursement",
    "Refunded": "Remboursé",
    "Register": "S'inscrire",
    "Registration": "Inscription",
    "Remove": "Retirer",
    "Removed": "Retiré",
    "Request": "Demande",
    "Requested": "Demandé",
    "Reset": "Réinitialiser",
    "Resend": "Renvoyer",
    "Retry": "Réessayer",
    "Return": "Retour",
    "Returned": "Retourné",
    "Review": "Avis",
    "Save": "Enregistrer",
    "Saved": "Enregistré",
    "Search": "Rechercher",
    "See": "Voir",
    "Select": "Sélectionner",
    "Selected": "Sélectionné",
    "Send": "Envoyer",
    "Sender": "Expéditeur",
    "Set": "Définir",
    "Share": "Partager",
    "Sign": "Signer",
    "Skip": "Passer",
    "Start": "Commencer",
    "Submit": "Soumettre",
    "Submitted": "Soumis",
    "Subscribe": "S'abonner",
    "Subscribed": "Abonné",
    "Switch": "Basculer",
    "Track": "Suivre",
    "Tracking": "Suivi",
    "Update": "Mettre à jour",
    "Updated": "Mis à jour",
    "Upload": "Télécharger",
    "Uploaded": "Téléchargé",
    "Use": "Utiliser",
    "Used": "Utilisé",
    "Verify": "Vérifier",
    "Verified": "Vérifié",
    "View": "Voir",
    "Wait": "Attendre",
    "Waiting": "En attente",
    "Write": "Écrire",
    
    # Noms
    "Account": "Compte",
    "Address": "Adresse",
    "Addresses": "Adresses",
    "Admin": "Administrateur",
    "Amount": "Montant",
    "Available": "Disponible",
    "Balance": "Solde",
    "Bank": "Banque",
    "Basic": "Basique",
    "Bill": "Facture",
    "Billing": "Facturation",
    "Booking": "Réservation",
    "Business": "Entreprise",
    "Campaign": "Campagne",
    "Campaigns": "Campagnes",
    "Car": "Voiture",
    "Cart": "Panier",
    "Cash": "Espèces",
    "Categories": "Catégories",
    "Category": "Catégorie",
    "Certificate": "Certificat",
    "Charge": "Frais",
    "Chat": "Discussion",
    "Checkout": "Paiement",
    "City": "Ville",
    "Code": "Code",
    "Comment": "Commentaire",
    "Comments": "Commentaires",
    "Contact": "Contact",
    "Conversation": "Conversation",
    "Cost": "Coût",
    "Coupon": "Coupon",
    "Cover": "Couverture",
    "Credit": "Crédit",
    "Currency": "Devise",
    "Customer": "Client",
    "Customers": "Clients",
    "Date": "Date",
    "Day": "Jour",
    "Days": "Jours",
    "Debit": "Débit",
    "Default": "Par défaut",
    "Delivery": "Livraison",
    "Deliveryman": "Livreur",
    "Description": "Description",
    "Destination": "Destination",
    "Details": "Détails",
    "Direction": "Direction",
    "Discount": "Réduction",
    "Discounted": "Réduit",
    "Distance": "Distance",
    "Driver": "Chauffeur",
    "Duration": "Durée",
    "Earnings": "Gains",
    "Email": "E-mail",
    "Error": "Erreur",
    "Estimate": "Estimation",
    "Estimated": "Estimé",
    "Expire": "Expiration",
    "Favorite": "Favori",
    "Favourite": "Favori",
    "Featured": "En vedette",
    "Fee": "Frais",
    "Filter": "Filtre",
    "Floor": "Étage",
    "Food": "Nourriture",
    "Free": "Gratuit",
    "Freelancer": "Indépendant",
    "General": "Général",
    "Guest": "Invité",
    "Help": "Aide",
    "History": "Historique",
    "Home": "Accueil",
    "Hour": "Heure",
    "Hourly": "Horaire",
    "Hours": "Heures",
    "House": "Maison",
    "ID": "ID",
    "Identity": "Identité",
    "Image": "Image",
    "Images": "Images",
    "Information": "Information",
    "Inside": "À l'intérieur",
    "Instant": "Instantané",
    "Invalid": "Invalide",
    "Invite": "Inviter",
    "Item": "Article",
    "Items": "Articles",
    "Kilometer": "Kilomètre",
    "Label": "Étiquette",
    "Language": "Langue",
    "Latitude": "Latitude",
    "License": "Licence",
    "Link": "Lien",
    "Links": "Liens",
    "List": "Liste",
    "Live": "En direct",
    "Location": "Emplacement",
    "Logo": "Logo",
    "Longitude": "Longitude",
    "Loyalty": "Fidélité",
    "Mail": "Courrier",
    "Map": "Carte",
    "Maximum": "Maximum",
    "Menu": "Menu",
    "Message": "Message",
    "Messages": "Messages",
    "Method": "Méthode",
    "Minimum": "Minimum",
    "Minute": "Minute",
    "Minutes": "Minutes",
    "Model": "Modèle",
    "Module": "Module",
    "Modules": "Modules",
    "Money": "Argent",
    "Month": "Mois",
    "Name": "Nom",
    "Nearby": "À proximité",
    "Nearest": "Plus proche",
    "New": "Nouveau",
    "News": "Actualités",
    "Newsletter": "Newsletter",
    "Next": "Suivant",
    "No": "Non",
    "Note": "Note",
    "Notes": "Notes",
    "Nothing": "Rien",
    "Notification": "Notification",
    "Notifications": "Notifications",
    "Now": "Maintenant",
    "Number": "Numéro",
    "Office": "Bureau",
    "Offline": "Hors ligne",
    "Ongoing": "En cours",
    "Online": "En ligne",
    "Open": "Ouvrir",
    "Opened": "Ouvert",
    "Opinion": "Opinion",
    "Option": "Option",
    "Options": "Options",
    "Optional": "Optionnel",
    "Order": "Commande",
    "Orders": "Commandes",
    "Others": "Autres",
    "Outside": "À l'extérieur",
    "Owner": "Propriétaire",
    "Parcel": "Colis",
    "Partial": "Partiel",
    "Passport": "Passeport",
    "Password": "Mot de passe",
    "Past": "Passé",
    "Payment": "Paiement",
    "Payments": "Paiements",
    "Person": "Personne",
    "Phone": "Téléphone",
    "Photo": "Photo",
    "Pickup": "Ramassage",
    "Place": "Lieu",
    "Platform": "Plateforme",
    "Point": "Point",
    "Points": "Points",
    "Policy": "Politique",
    "Popular": "Populaire",
    "Popularity": "Popularité",
    "Preference": "Préférence",
    "Premium": "Premium",
    "Prescription": "Ordonnance",
    "Price": "Prix",
    "Privacy": "Confidentialité",
    "Problem": "Problème",
    "Process": "Processus",
    "Product": "Produit",
    "Products": "Produits",
    "Profile": "Profil",
    "Promo": "Promo",
    "Promotional": "Promotionnel",
    "Provider": "Fournisseur",
    "Providers": "Fournisseurs",
    "Purchase": "Achat",
    "Quantity": "Quantité",
    "Quick": "Rapide",
    "Range": "Gamme",
    "Reason": "Raison",
    "Reasons": "Raisons",
    "Receiver": "Destinataire",
    "Recommended": "Recommandé",
    "Recommendations": "Recommandations",
    "Refer": "Parrainer",
    "Referral": "Parrainage",
    "Refund": "Remboursement",
    "Registration": "Inscription",
    "Rent": "Location",
    "Rental": "Location",
    "Required": "Requis",
    "Restaurant": "Restaurant",
    "Restaurants": "Restaurants",
    "Result": "Résultat",
    "Results": "Résultats",
    "Ride": "Course",
    "Road": "Route",
    "Route": "Itinéraire",
    "Running": "En cours",
    "Salary": "Salaire",
    "Same": "Même",
    "Schedule": "Horaire",
    "Scheduled": "Programmé",
    "Seat": "Siège",
    "Seller": "Vendeur",
    "Sender": "Expéditeur",
    "Service": "Service",
    "Services": "Services",
    "Settings": "Paramètres",
    "Share": "Partager",
    "Sharing": "Partage",
    "Shipping": "Expédition",
    "Shop": "Boutique",
    "Shopping": "Achats",
    "Since": "Depuis",
    "Social": "Social",
    "Something": "Quelque chose",
    "Sorry": "Désolé",
    "Special": "Spécial",
    "Standard": "Standard",
    "Status": "Statut",
    "Stock": "Stock",
    "Store": "Magasin",
    "Stores": "Magasins",
    "Street": "Rue",
    "Subscription": "Abonnement",
    "Subtotal": "Sous-total",
    "Success": "Succès",
    "Successful": "Réussi",
    "Successfully": "Avec succès",
    "Suggestion": "Suggestion",
    "Suggestions": "Suggestions",
    "Support": "Support",
    "Tax": "Taxe",
    "Taxi": "Taxi",
    "Terms": "Conditions",
    "Theme": "Thème",
    "Time": "Heure",
    "Tips": "Pourboires",
    "Today": "Aujourd'hui",
    "Tomorrow": "Demain",
    "Total": "Total",
    "Track": "Suivre",
    "Transaction": "Transaction",
    "Transactions": "Transactions",
    "Trip": "Trajet",
    "Trips": "Trajets",
    "Trusted": "De confiance",
    "Type": "Type",
    "Unavailable": "Indisponible",
    "Under": "Sous",
    "Unpaid": "Impayé",
    "Until": "Jusqu'à",
    "Valid": "Valide",
    "Variation": "Variation",
    "Variations": "Variations",
    "VAT": "TVA",
    "Vehicle": "Véhicule",
    "Vehicles": "Véhicules",
    "Vendor": "Vendeur",
    "Verification": "Vérification",
    "Version": "Version",
    "Video": "Vidéo",
    "Voice": "Voix",
    "Volume": "Volume",
    "Voucher": "Bon",
    "Wallet": "Portefeuille",
    "Warning": "Avertissement",
    "Way": "Chemin",
    "Week": "Semaine",
    "Whatsapp": "Whatsapp",
    "Wish": "Souhait",
    "Year": "Année",
    "Yes": "Oui",
    "Zone": "Zone",
    
    # Expressions courantes
    "Add to cart": "Ajouter au panier",
    "Already added": "Déjà ajouté",
    "Are you sure": "Êtes-vous sûr",
    "Back to": "Retour à",
    "Cash on delivery": "Paiement à la livraison",
    "Contact person": "Personne de contact",
    "Credit card": "Carte de crédit",
    "Dark mode": "Mode sombre",
    "Dark theme": "Thème sombre",
    "Digital payment": "Paiement numérique",
    "First name": "Prénom",
    "First order": "Première commande",
    "Free delivery": "Livraison gratuite",
    "Guest mode": "Mode invité",
    "Home delivery": "Livraison à domicile",
    "Identity number": "Numéro d'identité",
    "Identity type": "Type d'identité",
    "In stock": "En stock",
    "Item price": "Prix de l'article",
    "Last name": "Nom de famille",
    "Live chat": "Chat en direct",
    "My account": "Mon compte",
    "My address": "Mon adresse",
    "My cart": "Mon panier",
    "My orders": "Mes commandes",
    "My wallet": "Mon portefeuille",
    "New password": "Nouveau mot de passe",
    "No data found": "Aucune donnée trouvée",
    "Not available": "Non disponible",
    "Not found": "Non trouvé",
    "Not now": "Pas maintenant",
    "Not provided": "Non fourni",
    "Order amount": "Montant de la commande",
    "Order details": "Détails de la commande",
    "Order ID": "ID de commande",
    "Order now": "Commander maintenant",
    "Order tracking": "Suivi de commande",
    "Out of stock": "Rupture de stock",
    "Past trips": "Trajets passés",
    "Phone number": "Numéro de téléphone",
    "Place order": "Passer commande",
    "Please enter": "Veuillez entrer",
    "Please select": "Veuillez sélectionner",
    "Popular items": "Articles populaires",
    "Promo code": "Code promo",
    "Quick contact": "Contact rapide",
    "Quick links": "Liens rapides",
    "Refer code": "Code de parrainage",
    "Reset password": "Réinitialiser le mot de passe",
    "Ride sharing": "Covoiturage",
    "Save location": "Enregistrer l'emplacement",
    "Search address": "Rechercher une adresse",
    "Service fee": "Frais de service",
    "Sign in": "Se connecter",
    "Sign up": "S'inscrire",
    "Social login": "Connexion sociale",
    "Store name": "Nom du magasin",
    "Street number": "Numéro de rue",
    "Take away": "À emporter",
    "Tax included": "Taxe incluse",
    "Terms and conditions": "Termes et conditions",
    "Terms & Conditions": "Termes et conditions",
    "Total amount": "Montant total",
    "Total bill": "Facture totale",
    "Total order": "Commande totale",
    "Track order": "Suivre la commande",
    "Trip history": "Historique des trajets",
    "Update now": "Mettre à jour maintenant",
    "User deleted": "Utilisateur supprimé",
    "Valid until": "Valide jusqu'au",
    "Vehicle type": "Type de véhicule",
    "Verification code": "Code de vérification",
    "View all": "Voir tout",
    "View cart": "Voir le panier",
    "View details": "Voir les détails",
    "View more": "Voir plus",
    "Voice search": "Recherche vocale",
    "Wallet amount": "Montant du portefeuille",
    "Wallet balance": "Solde du portefeuille",
    "Wallet payment": "Paiement par portefeuille",
    "Your order": "Votre commande",
}

def translate_text(text):
    """Traduit un texte anglais en français"""
    if not text:
        return text
    
    # Cas spéciaux déjà traduits
    special_cases = {
        "Addons": "Suppléments",
        "Total Amount": "Montant total",
        "Add To Cart": "Ajouter au panier",
        "Item added to cart": "Article ajouté au panier",
        "Already Added in Cart": "Déjà ajouté au panier",
        "Out of Stock": "Rupture de stock",
        "My Cart": "Mon panier",
        "Removed from cart": "Retiré du panier",
        "Enter Promo Code": "Entrez le code promo",
        "Delivery Option": "Option de livraison",
        "Home Delivery": "Livraison à domicile",
        "Take Away": "À emporter",
        "Item Price": "Prix de l'article",
        "Vat/Tax": "TVA/Taxe",
        "Subtotal": "Sous-total",
        "Coupon Discount": "Réduction du coupon",
        "Delivery Fee": "Frais de livraison",
        "Deliver To": "Livrer à",
        "Place Order": "Passer commande",
        "My Orders": "Mes commandes",
        "Order ID": "ID de commande",
        "Track Order": "Suivre la commande",
        "Re-Order": "Recommander",
        "Privacy Policy": "Politique de confidentialité",
        "About Us": "À propos de nous",
        "Terms & Conditions": "Termes et conditions",
        "Help & Support": "Aide et support",
        "Type here.....": "Tapez ici.....",
        "Valid until": "Valide jusqu'au",
        "Are you sure want to logout?": "Êtes-vous sûr de vouloir vous déconnecter?",
        "Guest Mode": "Mode invité",
        "Now you are in guest mode.\\nPlease login to enjoy the more awesome features.": "Vous êtes maintenant en mode invité.\\nVeuillez vous connecter pour profiter de fonctionnalités supplémentaires.",
        "Change something to update": "Changez quelque chose pour mettre à jour",
        "View All": "Voir tout",
        "Your cart is empty": "Votre panier est vide",
        "No data found": "Aucune donnée trouvée",
        "You are not logged in": "Vous n'êtes pas connecté",
        "Login to Continue": "Connectez-vous pour continuer",
        "off on all categories": "de réduction sur toutes les catégories",
        "Set Location": "Définir l'emplacement",
        "Search address here": "Rechercher une adresse ici",
        "My Address": "Mon adresse",
        "Saved Address": "Adresse enregistrée",
        "Add New Address": "Ajouter une nouvelle adresse",
        "Delivery Address": "Adresse de livraison",
        "Add the location Correctly": "Ajoutez l'emplacement correctement",
        "Contact Person Name": "Nom de la personne de contact",
        "Contact Person Number": "Numéro de la personne de contact",
        "Label As": "Étiqueter comme",
        "Save Location": "Enregistrer l'emplacement",
        "Pick Address": "Choisir l'adresse",
        "Are you sure want to reset?": "Êtes-vous sûr de vouloir réinitialiser?",
    }
    
    if text in special_cases:
        return special_cases[text]
    
    # Essayer une traduction simple mot à mot
    result = text
    for eng, fr in translations.items():
        # Remplacer les mots entiers uniquement
        result = re.sub(r'\b' + re.escape(eng) + r'\b', fr, result, flags=re.IGNORECASE)
    
    return result

def main():
    # Charger le fichier anglais
    with open('assets/language/en.json', 'r', encoding='utf-8') as f:
        en_data = json.load(f)
    
    # Charger le fichier français existant
    with open('assets/language/fr.json', 'r', encoding='utf-8') as f:
        fr_data = json.load(f)
    
    # Traduire les clés manquantes
    count = 0
    for key, value in en_data.items():
        if key not in fr_data or fr_data[key] == value:
            # Traduire automatiquement
            translated = translate_text(value)
            fr_data[key] = translated
            count += 1
            print(f"Traduit: {key}: {value} -> {translated}")
    
    # Sauvegarder le fichier français mis à jour
    with open('assets/language/fr.json', 'w', encoding='utf-8') as f:
        json.dump(fr_data, f, ensure_ascii=False, indent=2)
    
    print(f"\n✅ Traduction terminée! {count} entrées traduites.")
    print(f"📝 Fichier sauvegardé: assets/language/fr.json")

if __name__ == "__main__":
    main()
